language: go

sudo: false

go:
  - 1.6
  - tip

install:
  - go get -u ./...
  - go get -u github.com/stretchr/testify/assert
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - go test -v -bench=. -benchmem -cover ./...
  - goveralls -v -service=travis-ci -repotoken=$COVERALLS_TOKEN
